/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.Controller;
import static Controller.Controller.connection;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Ben
 */
public class DeleteSequence extends javax.swing.JPanel {
    public Controller thisController = new Controller();
    /**
     * Creates new form DeleteSequence
     */
    boolean checkEdit =false;
    static int i = 0;
    public DeleteSequence() {
        
        if(i==1){
            thisController.connectiontoDB("openConn"); 
            initComponents();
            scriptText.setEditable(false);
            saveScript.setEnabled(false);
            View_List.clear();
            
            scriptText.setDisabledTextColor(Color.BLACK);
        }      
    }
    
    private ArrayList<String> View_List = new ArrayList<String>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancel = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        sequenceList = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        showScript = new javax.swing.JButton();
        editScript = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        scriptText = new javax.swing.JTextArea();
        saveScript = new javax.swing.JButton();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        cancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cancelKeyPressed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        delete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                deleteKeyPressed(evt);
            }
        });

        sequenceList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Please Select One--" }));

        jLabel2.setText("Select sequence");

        update.setIcon(thisController.refreshIcon(15));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        update.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                updateKeyPressed(evt);
            }
        });

        showScript.setText("Show Script");
        showScript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showScriptActionPerformed(evt);
            }
        });
        showScript.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                showScriptKeyPressed(evt);
            }
        });

        editScript.setText("Edit Script");
        editScript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editScriptActionPerformed(evt);
            }
        });
        editScript.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editScriptKeyPressed(evt);
            }
        });

        scriptText.setColumns(20);
        scriptText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        scriptText.setRows(5);
        jScrollPane1.setViewportView(scriptText);

        saveScript.setText("Save Script");
        saveScript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveScriptActionPerformed(evt);
            }
        });
        saveScript.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                saveScriptKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(update)
                        .addGap(29, 29, 29)
                        .addComponent(cancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(delete))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(editScript, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(showScript, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(saveScript, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sequenceList, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sequenceList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(showScript)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editScript)
                        .addGap(13, 13, 13)
                        .addComponent(saveScript))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delete)
                    .addComponent(cancel)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        if(!checkEdit){
            int checkSure = JOptionPane.showConfirmDialog(null, 
                       "Are you sure you want to delete the sequence?", "Notice", JOptionPane.YES_NO_OPTION);
            if(checkSure==0){ 
                boolean k = true;
                try {
                    String drop_Item = null;
                    drop_Item = (String) sequenceList.getSelectedItem();  
                    String script = "DROP SEQUENCE " + drop_Item;
                    thisController.connectiontoDB("openConn"); 
                    PreparedStatement st = connection.prepareStatement(script);
                    st.executeUpdate();
                    thisController.history(script);
                }catch (SQLException ex)
                {
                    k = false;
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", 
                            JOptionPane.ERROR_MESSAGE);
                }
                try {
                    connection.close();
                } 
                catch (SQLException ex1) 
                {
                  Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex1);
                }
                try{
                    thisController.connectiontoDB("openConn"); 
                    View_List.clear();
                    String script2 = "SELECT SEQUENCE_NAME FROM USER_SEQUENCES";
                    Statement stmQuery = connection.createStatement();
                    ResultSet rsQuery = stmQuery.executeQuery (script2);
                    while(rsQuery.next()){
                           View_List.add(rsQuery.getString(1));   
                    } 
                    sequenceList.removeAllItems();
                    sequenceList.addItem("--Please Select One--");
                    for(int i=0;i<View_List.size();i++)
                    {
                      sequenceList.addItem(View_List.get(i));
                    }
                }
                catch (SQLException ex)
                {
                   k= false;
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", 
                            JOptionPane.ERROR_MESSAGE);
                }
                try {
                    connection.close();
                } 
                catch (SQLException ex1) 
                {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex1);
                }
                if(k==true)
                {
                    JOptionPane.showMessageDialog(this,"SEQUENCE deleted");
                }
                scriptText.setText("");
            }
        }
        else
        {
            int checkSure = JOptionPane.showConfirmDialog(null, 
                       "Are you sure you want to delete the sequence?", "Notice", 
                       JOptionPane.YES_NO_OPTION);
            if(checkSure==0){ 
                boolean k = true;
                try {

                    String script = scriptText.getText();
                    thisController.connectiontoDB("openConn"); 
                    PreparedStatement st = connection.prepareStatement(script);
                    st.executeUpdate();
                    thisController.history(script);
                }catch (SQLException ex)
                {
                    k = false;
                    JOptionPane.showMessageDialog(this, ex.getMessage() , "Error", 
                            JOptionPane.ERROR_MESSAGE);
                }
                try {
                    connection.close();
                } 
                catch (SQLException ex1) 
                {
                  Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex1);
                }
                try{
                    thisController.connectiontoDB("openConn"); 
                    View_List.clear();
                    String script2 = "SELECT SEQUENCE_NAME FROM USER_SEQUENCES";
                    Statement stmQuery = connection.createStatement();
                    ResultSet rsQuery = stmQuery.executeQuery (script2);
                    while(rsQuery.next()){
                           View_List.add(rsQuery.getString(1));   
                    } 
                    sequenceList.removeAllItems();
                    sequenceList.addItem("--Please Select One--");
                    for(int i=0;i<View_List.size();i++)
                    {
                      sequenceList.addItem(View_List.get(i));
                    }
                }
                catch (SQLException ex)
                {
                   k= false;
                    JOptionPane.showMessageDialog(this, ex.getMessage() , "Error", 
                            JOptionPane.ERROR_MESSAGE);
                }
                try {
                    connection.close();
                } 
                catch (SQLException ex1) 
                {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex1);
                }
                if(k==true)
                {
                    JOptionPane.showMessageDialog(this,"SEQUENCE deleted");
                }
            }  
            scriptText.setText("");
        }
        
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
         try{
            thisController.connectiontoDB("openConn"); 
            View_List.clear();
            String script2 = "SELECT SEQUENCE_NAME FROM USER_SEQUENCES";
            Statement stmQuery = connection.createStatement();
            ResultSet rsQuery = stmQuery.executeQuery (script2);
            while(rsQuery.next()){
                   View_List.add(rsQuery.getString(1));   
            } 
            sequenceList.removeAllItems();
            sequenceList.addItem("--Please Select One--");
            for(int i=0;i<View_List.size();i++)
            {
              sequenceList.addItem(View_List.get(i));
            }
       }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        try {
            connection.close();
        } 
        catch (SQLException ex1) 
        {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex1);
        }

    }//GEN-LAST:event_updateActionPerformed

    private void showScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showScriptActionPerformed
        String drop_Item = null;
        drop_Item = (String) sequenceList.getSelectedItem();  
        String script = "DROP SEQUENCE " + drop_Item;
        scriptText.setText(script);
        saveScript.setEnabled(true);
    }//GEN-LAST:event_showScriptActionPerformed

    private void editScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editScriptActionPerformed
        scriptText.setEditable(true);
        checkEdit = true;
        saveScript.setEnabled(true);
    }//GEN-LAST:event_editScriptActionPerformed

    private void deleteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deleteKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            delete.doClick();
        }
    }//GEN-LAST:event_deleteKeyPressed

    private void showScriptKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_showScriptKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            showScript.doClick();
        }
    }//GEN-LAST:event_showScriptKeyPressed

    private void editScriptKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editScriptKeyPressed
          if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            editScript.doClick();
        }
    }//GEN-LAST:event_editScriptKeyPressed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        scriptText.setText("");
        saveScript.setEnabled(false);
        sequenceList.setSelectedIndex(0);
    }//GEN-LAST:event_cancelActionPerformed

    private void saveScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveScriptActionPerformed

        int val = 0;

        //set button name for fileChooser
        UIManager.put("FileChooser.openDialogTitleText", "Load Script File");
        UIManager.put("FileChooser.openButtonText", "Save Script");

        //Browse file from drive
        JFileChooser fileChooser = new JFileChooser();

        try {
            val = fileChooser.showOpenDialog(null);
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Error opening the file dialogue",
                null, JOptionPane.ERROR_MESSAGE);
        }

        //if file is approve to open start to save the script to that file
        if (val == JFileChooser.APPROVE_OPTION) {
            String saveScriptPath = fileChooser.getSelectedFile().getAbsolutePath();
            if(saveScriptPath.endsWith(".sql")){
                thisController.writeScrpitForSave(saveScriptPath,scriptText.getText());
            }else{
                saveScriptPath = saveScriptPath+".sql";
                thisController.writeScrpitForSave(saveScriptPath,scriptText.getText());
            }
            JOptionPane.showMessageDialog(null, "Script is Saved.");
        }
    }//GEN-LAST:event_saveScriptActionPerformed

    private void saveScriptKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saveScriptKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            saveScript.doClick();
        }
    }//GEN-LAST:event_saveScriptKeyPressed

    private void cancelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cancelKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            cancel.doClick();
        }
    }//GEN-LAST:event_cancelKeyPressed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        update.doClick();
    }//GEN-LAST:event_formAncestorAdded

    private void updateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            update.doClick();
        }
    }//GEN-LAST:event_updateKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JButton delete;
    private javax.swing.JButton editScript;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveScript;
    private javax.swing.JTextArea scriptText;
    private javax.swing.JComboBox sequenceList;
    private javax.swing.JButton showScript;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
